version: '3.8'

volumes:
  csv:

services:
  db:
    volumes:
      - csv:/home/tristan/HackReactor/SDC/csv:ro
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: qa
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: tristanlerisse@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"